--- ПРОГРАММА НА 3 ---
print("Введите номер месяца")
a = io.read("*n")

if a == 1 then print("январь, зима")
elseif a == 2 then print("февраль, зима")
elseif a == 3 then print("март, весна")
elseif a == 4 then print("апрель, весна")
elseif a == 5 then print("май, весна")
elseif a == 6 then print("июнь, лето")
elseif a == 7 then print("июль, лето")
elseif a == 8 then print("август, лето")
elseif a == 9 then print("сентябрь, осень")
elseif a == 10 then print("октябрь, осень")
elseif a == 11 then print("ноябрь, осень")
elseif a == 12 then print("декабрь, зима")
elseif a<1 then print("Вы ввели неправильную цифру")
elseif a>12 then print("Вы ввели неправильную цифру")
end


--- ПРОГРАММА НА 4 ---
print("Введите свой возраст")
a = io.read("*n")

if a>1 and a<5 then print("Мне ",a," года")
elseif a>4 and a<21 then print("Мне ",a," лет")
elseif a=21 then print("Мне ",a," год")
elseif a>21 and a<25 then print("Мне ",a," года")
elseif a>24 and a<31 then print("Мне ",a," лет")
elseif a=31 then print("Мне ",a," год")
elseif a>31 and a<35 then print("Мне ",a," года")
elseif a>34 and a<41 then print("Мне ",a," лет")
elseif a=41 then print("Мне ",a," год")
elseif a>41 and a<45 then print("Мне ",a," года")
elseif a>44 and a<51 then print("Мне ",a," лет")
elseif a=51 then print("Мне ",a," год")
elseif a>51 and a<55 then print("Мне ",a," года")
elseif a>54 and a<61 then print("Мне ",a," лет")
elseif a=61 then print("Мне ",a," год")
elseif a>61 and a<65 then print("Мне ",a," года")
elseif a>64 and a<71 then print("Мне ",a," лет")
elseif a=71 then print("Мне ",a," год")
elseif a>71 and a<75 then print("Мне ",a," года")
elseif a>74 and a<81 then print("Мне ",a," лет")
elseif a=81 then print("Мне ",a," год")
elseif a>81 and a<85 then print("Мне ",a," года")
elseif a>84 and a<91 then print("Мне ",a," лет")
elseif a=91 then print("Мне ",a," год")
elseif a>91 and a<95 then print("Мне ",a," года")
elseif a>94 and a<101 then print("Мне ",a," лет")
elseif a>100 then print("Vi slishkom star")
end